### ISSUE TITLE
Enable students to view grades

### ISSUE THREAD

**Issue by BelaReimberg** [BelaReimberg/practice-github-flow#2]
#Enable students to view the grades

#User story
* Student (user) story: I dislike seeing grades just on paper and having to calculate my average grade on my own. I can't know if I'm passing the class for this reason and I need a system that includes all grades on a single page and calculates my assignments and test grade's average.

#Task List
- [x] Make database to store grades
- [x] Make database for assignments/courses
- [x] Make HTML code for main page
- [x] Make assignments point to their corresponding courses
- [x] Display grade average for particular class
- [x] Let Student view grade info in more detail

#Acceptance Criteria
* Works for the duration of the semester
* Can work in Chrome and Safari
* Teachers can control what grades are shown

#Acceptance Testing
* Logged in user clicks grades tab
* grades should be displayed in a list for the particular student
* assignments/quizzes show up next to the grades
* average should be displayed on the top left
